### ISSUE TITLE
New C#-Based DET Framework

### ISSUE THREAD

**Issue by plitwin** [redcap-tools/redcap-tools.github.io#38]
I created a framework for creating .net-based data entry triggers for REDCap.
https://github.com/FredHutch/RedcapDotNetDETs

**Comment by plitwin** [comment]
Sorry I shouldn't have closed it. My bad.

**Comment by wibeasley** [comment]
@plitwin, thanks for getting our attention about this.  I've included it in the 'Code Samples' section  of the page (but haven't pulled it into the master branch yet).  

But I don't think that is the best term/location for it.  Is there a name you think makes more sense for your repo and Nefcy's repo?  

I don't think either belongs in the 'Library' section, because I think of libraries as being updatable by something like NuGet's [`update`](https://docs.microsoft.com/en-us/nuget/tools/cli-ref-update).

**Comment by wibeasley** [comment]
@plitwin, I'm closing this issue.  It's in the master branch now.  Tell me if you think of a different type of header you like.
